### ISSUE TITLE
Will you share the pre-trianed model and test cases?

### ISSUE THREAD

**Issue by willie1997** [jiashunwang/Neural-Pose-Transfer#1]
Would you please sahre the pretrained model and the demo code? I hope to test this model on my own data. Also, how to set the training data? Looking forward to your reply!

**Comment by walsvid** [comment]
We will release checkpoint and demo code as soon as possible.

**Comment by walsvid** [comment]
@willie1997 We have upload the checkpoint files and demo code. Please check README for more information. I'll close this issue. Feel free to reopen it if there is any further question.
