### ISSUE TITLE
Question about Permutation Invariant Pose Feature Extractor

### ISSUE THREAD

**Issue by 07hyx06** [jiashunwang/Neural-Pose-Transfer#12]
Thanks for your great work! 
But I wonder why the model works on target and source mesh with a different vertex order. The feature F_pose extracted from the Encoder seems to be different on the same pose mesh with different vertex order. Also, F_pose is not spatially aligned with the vertex of the identity mesh. Does Pose1(order 1) + Identity1 and Pose1(order 2) + Identity1 outputs nearly the same result? Any insights on why it works on different vertex order inputs?

**Comment by jiashunwang** [comment]
Hi @07hyx06,
This is a very good question. 
Firstly, Pose1(order 1) + Identity1 and Pose1(order 2) + Identity1 outputs nearly the same result no matter you use original or maxpool.
For original model, we think it is the Instance Norm in each chanel exchang some information.
For maxpool, it is a global feature.
Thank you for your question.

**Comment by 07hyx06** [comment]
Thanks for your reply!
So there are no explicit modules to keep the results invariant to vertex permutation, it can still reach good results even though the pose and identity features are not spatially aligned?

**Comment by jiashunwang** [comment]
Hi @07hyx06 
Through the experiments, it can reach good results using the architecture in our paper directly.
