### ISSUE TITLE
Reg. SMPL based dataset

### ISSUE THREAD

**Issue by jaygit123** [jiashunwang/Neural-Pose-Transfer#3]
Hi @jiashunwang,
I understand that we can use the .obj files created by SMPL based models as dataset. 
Do let me know if there is any constraints like entire 3D object should be visible, etc.

Ca you share sample dataset that you used for training? That will help me understand how to create dataset for training. 

Thanks

**Comment by walsvid** [comment]
The training data is comming soon.
