### ISSUE TITLE
no permission to the pre-trained models

### ISSUE THREAD

**Issue by alaist** [jiashunwang/Neural-Pose-Transfer#4]
I've tried to download the pre-trained models in http://www.sdspeople.fudan.edu.cn/fuyanwei/download/NeuralPoseTransfer/ckpt/, 
but I met the forbidden: "You don't have permission to access /fuyanwei/download/NeuralPoseTransfer/ckpt/original.model on this server"
Have I missed any authentication steps?

**Comment by alaist** [comment]
now it's opened

**Comment by buaaswf** [comment]
I meet the same problem in filelists/ data link.
Please help me,
Thanks.

**Comment by walsvid** [comment]
Hi, @buaaswf. Sorry for the late reply. I have updated the permissions of the server data and it should be able to download normally now.
